export const FETCH_USER_REQUEST ='FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS ='FETCH_USER_SUCCESS'
export const FETCH_USER_SUCCESS2 ='FETCH_USER_SUCCESS2'

export const FETCH_USER_FAILURE ='FETCH_USER_FAILURE'
export const FETCH_USER_FAILURE2 ='FETCH_USER_FAILURE2'




